version: "3"
services:
  nodeapp:
    image: node:14
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 4
    volumes:
      - ./app:/usr/src/app
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodeapp
